
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Qoriatul Masfufah
 */
public class Volume_Bangun_Ruang extends javax.swing.JFrame {

    /**
     * Creates new form Volume_Bangun_Ruang
     */
    public Volume_Bangun_Ruang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPanjang = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        tfLebar = new javax.swing.JTextField();
        btnBalok = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfSisi = new javax.swing.JTextField();
        btnKubus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jfJari = new javax.swing.JTextField();
        btnBola = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 260, 15);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Masukkan Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(25, 23, 120, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Masukkan Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(25, 61, 110, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Masukkan Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(25, 95, 110, 14);
        jPanel1.add(tfPanjang);
        tfPanjang.setBounds(164, 17, 104, 27);
        jPanel1.add(tfTinggi);
        tfTinggi.setBounds(164, 88, 104, 28);
        jPanel1.add(tfLebar);
        tfLebar.setBounds(164, 55, 104, 27);

        btnBalok.setText("Hitung");
        btnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(btnBalok);
        btnBalok.setBounds(164, 127, 94, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("cm");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 90, 17, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 20, 17, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("cm");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(280, 60, 17, 20);

        jTabbedPane2.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(28, 22, 140, 14);
        jPanel2.add(tfSisi);
        tfSisi.setBounds(28, 42, 116, 29);

        btnKubus.setText("Volume");
        btnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(btnKubus);
        btnKubus.setBounds(28, 89, 80, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(150, 50, 17, 15);

        jTabbedPane2.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Masukkan Panjang Jari-jari");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(34, 11, 165, 14);
        jPanel3.add(jfJari);
        jfJari.setBounds(34, 36, 96, 30);

        btnBola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBola.setText("Volume");
        btnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBola);
        btnBola.setBounds(34, 77, 75, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("cm");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(140, 44, 17, 14);

        jTabbedPane2.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 40, 400, 260);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalokActionPerformed
        // TODO add your handling code here:
        int panjang,lebar, tinggi;
        panjang=Integer.parseInt(tfPanjang.getText());
        lebar=Integer.parseInt(tfLebar.getText());
        tinggi=Integer.parseInt(tfTinggi.getText());
        int hasil=panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok Adalah :"+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eror:"+ e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBalokActionPerformed

    private void btnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi=Integer.parseInt(tfSisi.getText());
        int hasil=sisi*sisi*sisi;

        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus adalah :"
                +hasil, "luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Eror:"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnKubusActionPerformed

    private void btnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari= Integer.parseInt(jfJari.getText());
        float hasil1=(float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Luas Permukaan Bola adalah :"
                +hasil1,"luas",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,"Eror"+e,"Gagal",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Volume_Bangun_Ruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Volume_Bangun_Ruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Volume_Bangun_Ruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Volume_Bangun_Ruang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Volume_Bangun_Ruang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBalok;
    private javax.swing.JButton btnBola;
    private javax.swing.JButton btnKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jfJari;
    private javax.swing.JTextField tfLebar;
    private javax.swing.JTextField tfPanjang;
    private javax.swing.JTextField tfSisi;
    private javax.swing.JTextField tfTinggi;
    // End of variables declaration//GEN-END:variables
}
